// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SSDTEssentials
{
    internal sealed partial class Vsix
    {
        public const string Id = "SSDTEssentials.24111459-78ad-40dc-a2a3-476931836760";
        public const string Name = "SSDT Essentials";
        public const string Description = @"Essential tools for development of an SSDT database project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Brian Savignano";
        public const string Tags = "";
    }
}
