// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SSDTEssentials
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SSDTEssentialsString = "ca1659ef-d2d5-41ad-b1d5-11f7cecda18f";
        public static Guid SSDTEssentials = new Guid(SSDTEssentialsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SSDTEssentialsTopMenu = 0x1000;
        public const int SSDTEssentialsMenuGroup = 0x0001;
        public const int FixUnnamedConstraintsCommand = 0x0100;
    }
}